# Generated by Django 4.0.1 on 2023-06-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Zutat', 'verbose_name_plural': 'Zutaten'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Rezept', 'verbose_name_plural': 'Rezepte'},
        ),
    ]
