# Generated by Django 4.0.1 on 2023-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Woche', 'verbose_name_plural': 'Wochen'},
        ),
        migrations.AddField(
            model_name='day',
            name='dinner_freestyle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Notiz'),
        ),
    ]
